# FILL AND RENAME TO sdkconfig.defaults TO USE

# App Version
CONFIG_APP_PROJECT_VER_FROM_CONFIG=y
CONFIG_APP_PROJECT_VER="v0.0.3"

# Wi-Fi
CONFIG_WIFI_SSID="YourWiFiSSID"
CONFIG_WIFI_PASS="YourWiFiPassword"

# MQTT
CONFIG_MQTT_BROKER_URI="mqtt://192.168.1.100:1883"
CONFIG_MQTT_DEVICE_NAME="Meteopod Dev - Example"

# Flash size
CONFIG_ESPTOOLPY_FLASHSIZE_4MB=y

# OTA related
CONFIG_ESP_HTTPS_OTA_ALLOW_HTTP=y
CONFIG_PARTITION_TABLE_CUSTOM=y
CONFIG_PARTITION_TABLE_CUSTOM_FILENAME="partitions.csv"
CONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE=y
CONFIG_BOOTLOADER_APP_ELF_SHA256=y
CONFIG_OTA_DATA_ERASE=y
CONFIG_OTA_FIRMWARE_URL="http://192.168.1.100:9000/firmware/esp32-meteopod.bin"
