name: Build ESP32 Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]

    env:
      IDF_VERSION: v5.4.1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with ESP-IDF
      shell: bash
      run: |
        source /opt/esp-idf/export.sh
        idf.py build

  flash:
    needs: build
    runs-on: [self-hosted, Linux, X64]

    env:
      IDF_VERSION: v5.4.1

    steps:
    - name: Flash with ESP-IDF
      shell: bash
      run: |
        source /opt/esp-idf/export.sh
        idf.py -p /dev/ttyUSB1 flash

  monitor_output:
    needs: flash
    runs-on: [self-hosted, Linux, X64]

    env:
      IDF_VERSION: v5.4.1

    steps:
    - name: Flash with ESP-IDF
      shell: bash
      run: |
        source /opt/esp-idf/export.sh
        
        # Monitor for 30 seconds, look for expected strings
        timeout 30 idf.py -p /dev/ttyUSB1 monitor | tee monitor.log | grep -q 'SYSTEM_MONITOR: Uptime'

        if [ $? -eq 0 ]; then
          echo "Expected output found in serial log."
        else
          echo "Expected output NOT found."
          echo "Monitor log:"
          cat monitor.log
          exit 1
        fi