name: Build ESP32 Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]

    env:
      IDF_VERSION: v5.4.1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with ESP-IDF
      shell: bash
      run: |
        export IDF_PYTHON_ENV_PATH=/root/.espressif/python_env/idf5.4_py3.11_env
        source /opt/esp-idf/export.sh
        idf.py build
