name: Build ESP32 Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, esp32]

    env:
      IDF_VERSION: v5.4.1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Project
      run: |
        source /opt/esp-idf/export.sh
        idf.py set-target esp32
        idf.py build
