name: Build ESP32 Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]

    env:
      IDF_VERSION: v5.4.1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with ESP-IDF
      shell: bash
      run: |
        source /opt/esp-idf/export.sh
        idf.py build

  flash:
    needs: build
    runs-on: [self-hosted, Linux, X64]

    env:
      IDF_VERSION: v5.4.1

    steps:
    - name: Flash with ESP-IDF
      shell: bash
      run: |
        source /opt/esp-idf/export.sh
        idf.py -p /dev/ttyUSB1 flash

  monitor_output:
    needs: flash
    runs-on: [self-hosted, Linux, X64]

    env:
      IDF_VERSION: v5.4.1

    steps:
    - name: Monitor serial output after flassing
      shell: bash
      run: |
        source /opt/esp-idf/export.sh
        idf.py -p /dev/ttyUSB1 flash