name: ESP32 Unit Tests on Hardware

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hw-test:
    name: Run Unit Tests on ESP32
    runs-on: [self-hosted, linux, esp32-hw]   # your self-hosted runner tags
    steps:
      - uses: actions/checkout@v4

      - name: Install ESP-IDF & toolchain  
        uses: espressif/install-esp-idf-action@v1       # Installs IDF, tools & sets up env :contentReference[oaicite:0]{index=0}  
        with:
          version: "v5.4"                               # or whichever ESP-IDF you’re on

      - name: Install pytest-embedded dependencies  
        run: |
          python3 -m pip install --upgrade pytest pytest-embedded pytest-rerunfailures pytest-ignore-test-results

      - name: Build & flash Unity test app  
        run: idf.py -C tools/unit-test-app -T all flash  # builds + flashes all tests :contentReference[oaicite:1]{index=1}  
        env:
          IDF_PORT: /dev/ttyUSB1                         # or ${{ secrets.ESP_SERIAL_PORT }}

      - name: Run on-target tests via pytest  
        run: |
          pytest \
            --target esp32 \
            --serial-port /dev/ttyUSB1 \
            --baud 115200 \
            --exitfirst                              # stop on first failure  
        # pytest-embedded’s default markers will pick up your unity-app and run all cases :contentReference[oaicite:2]{index=2}
